#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif
#include "print.h" // Include for debugging

// Define the encoder map
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [1] = { ENCODER_CCW_CW(RGB_VAD, RGB_VAI) }
};

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_PSCR, KC_MUTE,
        KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC, KC_DEL,
        KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS, KC_HOME,
        KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, KC_END,
        KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_UP, KC_RGUI,
        KC_CAPS, KC_LGUI, KC_LALT, KC_SPC, KC_RALT, MO(1), KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
    ),
    [1] = LAYOUT(
        KC_TRNS, KC_MYCM, KC_WHOM, KC_CALC, KC_MSEL, KC_MPRV, KC_MNXT, KC_MPLY, KC_MSTP, KC_MUTE, KC_VOLD, KC_VOLU, KC_TRNS, KC_TRNS, QK_BOOT,
        RGB_M_T, RGB_M_P, RGB_M_B, RGB_M_R, RGB_M_SW, RGB_M_SN, RGB_M_K, RGB_M_X, RGB_M_G, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_INS,
        KC_TRNS, RGB_SPI, RGB_SPD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, BL_STEP, BL_BRTG, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        RM_VALU, RM_HUEU, RM_VALD, KC_TRNS, KC_TRNS, NK_TOGG, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_VAI, KC_TRNS, KC_TRNS, AG_NORM,
        AG_SWAP, RGB_TOG, KC_TRNS, KC_TRNS, KC_TRNS, RGB_RMOD, RGB_VAD, RGB_MOD
    )
};

#include "rgb_matrix.h"

// Variables to save the original RGB values
static uint8_t saved_hue, saved_sat, saved_val;
static bool caps_lock_active = false;

// Initialize backlight at 100% green
void keyboard_post_init_user(void) {
    rgb_matrix_enable();                 // Enable RGB
    rgb_matrix_mode_noeeprom(RGB_MATRIX_SOLID_COLOR);
    rgb_matrix_sethsv_noeeprom(85, 255, 255); // Green at 100% brightness
}

// Save backlight state before changing for Caps Lock
void set_backlight_red(void) {
    saved_hue = rgb_matrix_get_hue();
    saved_sat = rgb_matrix_get_sat();
    saved_val = rgb_matrix_get_val();
    rgb_matrix_sethsv_noeeprom(0, 255, 255); // Red at 100% brightness
}

void restore_backlight(void) {
    // Explicitly set the backlight to green
    rgb_matrix_sethsv_noeeprom(85, 255, 255); // Green at 100% brightness
}

// Add a new function to set the backlight to blue
void set_backlight_blue(void) {
    rgb_matrix_sethsv_noeeprom(160, 255, 255); // Blue at 100% brightness
}

// Remove the function key checks from led_update_user
bool led_update_user(led_t led_state) {
    if (led_state.caps_lock && !caps_lock_active) {
        set_backlight_red();
        caps_lock_active = true;
    } else if (!led_state.caps_lock && caps_lock_active) {
        restore_backlight();
        caps_lock_active = false;
    }

    return true;
}

// Modify the process_record_user function to handle the function key
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    static bool fn_key_active = false; // Track the state of the function key

    if (keycode == MO(1)) { // Check for the MO(1) keycode
        if (record->event.pressed) {
            if (!fn_key_active) {
                fn_key_active = true; // Mark the function key as active
                set_backlight_blue();
            }
        } else {
            if (fn_key_active) {
                fn_key_active = false; // Mark the function key as inactive
                restore_backlight(); // Restore the previous backlight state
            }
        }
        return true; // Allow further processing of this key to switch layers
    }

    return true; // Process other keys normally
}

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C
